### ISSUE TITLE
Improve Composer installation process

### ISSUE THREAD

**Issue by aleksip** [pattern-lab/edition-php-drupal-standard#1]
Error-free installation with Composer is currently not possible.

One workararound is to use a composer.lock edited to have a working package installation order.

Related pull request 
pattern-lab/patternlab-php-core#9

Related issues
pattern-lab/patternlab-php-core#13
pattern-lab/patternlab-php-core#14

**Comment by EvanLovely** [comment]
Our current setup that has `composer.lock` committed results in a successful install by ensuring the pieces are installed in the correct order. The only downside is this Edition requests that people runs `composer update` right after `composer create-project pattern-lab/edition-drupal-standard`. So basically for anybody using this: you're good and shouldn't install issues (just run `composer update` right after setup)

**Comment by EvanLovely** [comment]
OK, this is in `master` now!! Let's test and close this out; I'm seeing everything working good and not having to manually edit the `composer update` results in `composer.lock`. What do you see?

**Comment by EvanLovely** [comment]
OK, this problem is back.

**Comment by EvanLovely** [comment]
Awesome! Ok, so in 8a4e1b2 I moved `plugin-data-transform` from `require` to `require-dev` and that places it at the bottom of the `composer.lock` file and therefore installs after the other pieces as it needs to & I'm getting a successful install as of `v1.1.2`.

**Comment by dmolsen** [comment]
Is there something it definitely needs to be installed after?

**Comment by EvanLovely** [comment]
@dmolsen When it wasn't working before fix I just did; the contents of `packages/listeners.json` was this:

```json
{ "listeners": [ ] }
```

Now that the fix is in place, it's contents is:

```json
{"listeners":["\\aleksip\\DataTransformPlugin\\PatternLabListener"]}
```

I'm sure @aleksip could shed more light on why. Happy to see it fixed though!

**Comment by dmolsen** [comment]
I've been researching this. Ultimately I think my process is wrong. I think I need to use `post-install-cmd` and `post-update-cmd` events which run after the packages are installed and then go back and install all the associated assets. Maybe track installed versions in a config file and compare against `composer.lock` to know when to attempt to install things. Switching to `./vendor` for all the things will help some as well.

This way I wouldn't have to worry about install order which I think is, even in your small set-up, a pain in the ass to attempt to workaround. I think this would mean a full point release for core. Easy enough to do... just a big behind-the-scenes change.

**Comment by EvanLovely** [comment]
Reopening & renaming this issue to better track this conversation as an improvement.

**Comment by EvanLovely** [comment]
@dmolsen So the thing I've been noticing that could use improvements relates to how pattern-lab/plugin-drupal-twig-components works with this: it has files that get copied in after `composer update` only; it would be great if they get copied in after a `composer create-project`. With the current setup, I have to commit the [`source/_twig-components/`](https://github.com/pattern-lab/edition-php-drupal-standard/tree/master/source/_twig-components) folder because if someone creates a new project from here, then they wouldn't be present if I didn't commit them. It works for now, because if the Drupal Twig Components gets an update, and `composer update` is ran, then it copies in the new ones, overwriting the old ones. I'm open to different solutions, but would love if those files didn't need to be a part of this repo as I'm sure that will confuse contributors.

**Comment by dmolsen** [comment]
@EvanLovely -

I'll look into it. It doesn't make much sense as there's no reason it should only be copied on "update." The hook events right now are package install and update. Must be a package install ordering issue which, again, seems to be the main bugaboo.

**Comment by EvanLovely** [comment]
I believe what happens currently to get them moved in after `composer update` is this (all from PL Core's `InstallerUtil.php`):

- `runTasks($event, "update")`
- `parseComposerExtraList()`
- `parseFileList()`
- `movefiles()`

I don't believe `postCreateProjectCmd()` fires those off...

**Comment by dmolsen** [comment]
@EvanLovely -

I think I know the issue with files disappearing. I'm going to test further but I believe it's an order of operation issue. And all of those functions were firing on `postPackageInstall()` for each and every package. The `postCreateProjectCmd()` comes along and might accidentally clean `./source/`.

**Comment by dmolsen** [comment]
Continuing this conversation in pattern-lab/patternlab-php-core#14. We will need to test the install process on this repo so it's fine to keep this thread open.
