### ISSUE TITLE
edit styleguidekit-assets-default

### ISSUE THREAD

**Issue by ensk** [pattern-lab/edition-php-drupal-standard#15]
i'm a bit confuse on how to edit and work with styleguidekit-assets-default to add my custom styles...
somebody knows what is the best way to work with this ?? thanks for help

**Comment by dmolsen** [comment]
Before I offer an answer what, specifically, are you trying to style? The "viewer" or any molecules, organisms, etc that you might develop? Just want to make sure I point you in the correct direction. Thanks.

**Comment by ensk** [comment]
i want to add custom styles for my atoms(colors and fonts),and find the way to modify sass o css files of the styleguide for future changes

**Comment by EvanLovely** [comment]
You can always add a `<link>` to any stylesheet you want in `source/_meta/_00-head.twig`. All patterns compile exactly two directories deep so if you had `style.css` right next to `public/` you'd add this:

       <link rel="stylesheet" href="../../style.css">

**Comment by EvanLovely** [comment]
Let us know if you have any other questions! Happy Pattern Labbing!
