### ISSUE TITLE
a way to use single data json file to header and footer

### ISSUE THREAD

**Issue by ensk** [pattern-lab/edition-php-drupal-standard#19]
why?

1. I want my files are the same drupal will use (if possible) to simply move them to the theme

2. I want to easily change the data of header / footer and blocks to create themes with multiple config

at present I have several templates with its unique json file with the data. each file json I have to repeat the data for the header and footer which becomes a problem to achieve point 2

the structure I'm using is
one page.html.twig file which extend all my templates
```
{% extends  layout_base ~ ".html.twig" %}

{% block page_header %}
	{% include directory ~ 'organisms-header' %}
{% endblock %}

{% block page_footer %}
	{% include directory ~ 'organisms-footer' %}
{% endblock %}

```
the header / footer files only extend the layout

if I create a file header_strucure.json within the data folder, I have the following error
example of data.
```
{
	"page": {
		"branding": {
			"include()": {
				"pattern": "organisms-region.html",
				"with": {
					"attributes": {
						"Attribute()": {
							"class": ["l-region l-region--branding"]
						}
					},
					"content": {
						"include()": {
							"pattern": "molecules-block--system-branding-block.html"
						}
					}
				}
			}
		},
		"header_first": {
			"include()": {
				"pattern": "organisms-region.html",
				"with": {
					"attributes": {
						"Attribute()": {
							"class": ["l-region l-region--header-first"]
						}
					},
					"content": {
						"include()": {
							"pattern": "molecules-block-main-navigation"
						}
					}
				}
			}
		}
	}
}
```
```
Segmentation fault (core dumped)
```
if I create a json file for the header / footer where are the corresponding files twig, the data is ignored
if put the data inside a header.json where is my organisms the data is ignored ...

the main problem is to keep the data of the header and footer in one place

there is a way to do what I want ??
thanks for the help

**Comment by aleksip** [comment]
Hi ensk, are you using `plugin-data-transform` 1.0.0?

**Comment by ensk** [comment]
i'm using  one of the first version of this edition and my composer file:
```
"require-dev": {
        "aleksip/plugin-data-transform": "dev-master"
    }
```
I don't know where or how to check the version, but that is in my composer file
I go to  install the new version of patternlab to test

**Comment by ensk** [comment]
i test with ``` plugin-data-transform ``` 1.0.0 and the same result

**Comment by aleksip** [comment]
Moving this issue to [aleksip/plugin-data-transform#6](https://github.com/aleksip/plugin-data-transform/issues/6) and closing here as it is about a bug in `plugin-data-transform`.
