### ISSUE TITLE
StarterKits don't install in Linux

### ISSUE THREAD

**Issue by aleksip** [pattern-lab/edition-php-drupal-standard#2]
Installing StarterKits using core/console is currently not possible.

Related issue pattern-lab/edition-php-twig-standard#11
Related pull request pattern-lab/patternlab-php-core#12

**Comment by abhigupta** [comment]
Tried out the Pull request and it worked as expected.

**Comment by EvanLovely** [comment]
I ran `php core/console --starterkit --install pattern-lab/starterkit-twig-drupal-minimal` after installing this and got it to work!

**Comment by aleksip** [comment]
Got it to work on OS X. It seems that the downloaded StarterKit tar file is extracted differently on Linux and OS X.

**Comment by EvanLovely** [comment]
Hmmm...  Have the file and & line number this happens on?

We could put Linux specific instructions in our readme in the meantime.

**Comment by aleksip** [comment]
@EvanLovely It all happens in `\PatternLab\Fetch->fetchStarterKit` in core. I'll have a go at a cross-platform fix tomorrow. Unless you beat me to it of course! ;)

**Comment by EvanLovely** [comment]
As we've got this working fine on Macs; I've changed the title to reflect that this is a Linux issue for now.

**Comment by aleksip** [comment]
I think this can now be closed as pattern-lab/patternlab-php-core#12 is merged and released.
