### ISSUE TITLE
Error after selecting a starterkit on windows

### ISSUE THREAD

**Issue by mortona42** [pattern-lab/edition-php-drupal-standard#20]
I got this error during the composer install, after selecting the pattern-lab/starterkit-twig-drupal-minimal option.  Other options fail as well.  Works on my mac though.

`choose an option or hit return to skip: (ex. 1) > 1

downloading the starterkit...
finished downloading the starterkit...
Script PatternLab\Installer::postInstallCmd handling the post-install-cmd event terminated with an exception
 
 [Alchemy\Zippy\Exception\RuntimeException]
  Unable to execute the following command "C:\Program Files\Git\usr\bin\tar.E
  XE" "--extract" "--file=C:\Users\Andrew\AppData\Local\Temp\pl-sk\pl-BBCB.tm
  p" "--overwrite-dir" "--overwrite" "--gzip" "--directory" "C:\Users\Andrew\
  AppData\Local\Temp\pl-sk\pl-sk-archive" {output:       1 [main] tar 4132 C:
  \Program Files\Git\usr\bin\tar.exe: *** fatal error in forked process - for
  k: can't reserve memory for parent stack 0x600000 - 0x800000, (child has 0x
  400000 - 0x600000), Win32 error 487
     5694 [main] tar 4132 cygwin_exception::open_stackdumpfile: Dumping stack
   trace to tar.exe.stackdump
        1 [main] tar 2640 fork: child -1 - forked process 4132 died unexpecte
  dly, retry 0, exit code 0x100, errno 11
  /usr/bin/tar: child process: Cannot fork: Resource temporarily unavailable
  /usr/bin/tar: Error is not recoverable: exiting now
  }
`

**Comment by dmolsen** [comment]
@mortona42 -

Zippy seems like a hit or miss cross-platform library for dealing with zip files. Later version of core properly catch this exception and alert the user they can simply download the files themselves and put them in `./source`. That's all this step is doing. We need to get the Drupal Standard Edition updated.

**Comment by aleksip** [comment]
@dmolsen The `master` branch of Drupal Standard Edition already has core ^2.7.0 dependency, so if this problem is fixed in 2.7.0 it is just a matter of making a new release.

@EvanLovely Possible you could check the commits since 2.1.1 and make the release?

**Comment by Sweetchuck** [comment]
Same problem on Linux
<pre>
> PatternLab\Installer::postInstallCmd

suggested starterkits that work with this edition:

  1: pattern-lab/starterkit-twig-drupal-minimal
  2: pattern-lab/starterkit-twig-demo
  3: aleksip/starterkit-shila-drupal-theme
  4: forumone/starterkit-twig-drupal-gesso

choose an option or hit return to skip: (ex. 1) > 4

downloading the starterkit...
finished downloading the starterkit...
Script PatternLab\Installer::postInstallCmd handling the post-install-cmd event terminated with an exception


  [Alchemy\Zippy\Exception\RuntimeException]
  Unable to execute the following command '/bin/tar' '--extract' '--file=/tmp/pl-sk/pl-sk-archive.tar.gz27MDHX' '--overwrite-dir' '--overwrite' '--gzip' '--directory' '/tmp/pl-sk
  /pl-sk-archive' {output: /bin/tar: '--overwrite' cannot be used with '--overwrite-dir'
  Try '/bin/tar --help' or '/bin/tar --usage' for more information.
  }
</pre>

`$ which tar`
> /bin/tar

**Comment by aleksip** [comment]
I went ahead and made a new Drupal Standard Edition release with a core ^2.7.0 dependency.

@dmolsen However if this only means that the exception will be catched and Zippy does not work on either Windows or Linux maybe a core issue should be opened?

**Comment by dmolsen** [comment]
Feel free to. Again, this feature is a convenience method as opposed to something integral to how PL works tho.

**Comment by aleksip** [comment]
Ok, closing this issue here. Just tried StarterKit installation on Linux and it worked for me.
