### ISSUE TITLE
"composer start --timeout=0" gives an error

### ISSUE THREAD

**Issue by Bubbi** [pattern-lab/edition-php-drupal-standard#27]
In Readme.md, the following is specified:

> One line start
> This will compile PL and watch for changes while running the local server:
> composer start --timeout=0

But it is not working. I get the following error:

>   [Symfony\Component\Console\Exception\RuntimeException]
>   The "--timeout" option does not exist.

Is a different parameter required to make it work or is it an old function, that don't work anymore?

I'm using a ubuntu 14.04 running in a vagrant env.

**Comment by backlineint** [comment]
@Bubbi I'be been using 'composer run-script start --timeout=0' as an alternative.  Does that work for you?

**Comment by antbrown** [comment]
I was getting the same error, the solution from @backlineint works for me, thanks!
